@extends('garden.layout')
@section('content')
<section id="garden" class="opening-woodland"><div class="opening-caption"><p class="eyebrow">WORK, WONDER & THE THINGS IN BETWEEN</p><h1>A life with many branches.</h1><p>{{ $settings?->introduction??'Follow a little curiosity. See where it grows.' }}</p></div>@include('garden.tree')<div class="scene-invitation"><span aria-hidden="true">↓</span><a href="#selected-work">Wander a little further</a></div></section>
<section id="selected-work" class="section woodland-work"><div class="section-heading"><div><p class="eyebrow">FRUIT FROM THE BRANCHES</p><h2>Things brought to life.</h2></div><a class="text-link" href="{{ route('work') }}">All selected work ↗</a></div><div class="card-grid selected-grid">@forelse($selected as $item)@include('garden.card')@empty<p>Selected work will appear here as it’s published.</p>@endforelse</div></section>
<section class="section growing-section"><div class="section-heading"><div><p class="eyebrow">SMALL BEGINNINGS, NEW DIRECTIONS</p><h2>Currently growing.</h2></div><a href="{{ route('now') }}" class="text-link">What I’m doing now ↗</a></div><div class="card-grid">@foreach($growing as $item)@include('garden.card')@endforeach</div></section>
<section class="section field-notes"><div class="section-heading"><div><p class="eyebrow">NOTES FROM THE WOODLAND</p><h2>A quieter place to read.</h2></div><a class="text-link" href="{{ route('blogs') }}">Blogs & Guides ↗</a></div><div class="notes-list">@foreach($recent as $item)<a href="{{ route('entry',$item->slug) }}"><span>{{ $item->meaningful_updated_at?->format('d M Y') }}</span><h3>{{ $item->title }}</h3><small>{{ ucfirst($item->type) }}</small><b>↗</b></a>@endforeach</div><div class="reading-journeys"><p class="eyebrow">FOLLOW A FAMILIAR PATH</p><a class="text-link" href="{{ route('channels') }}">Explore the channels ↗</a><a class="text-link" href="{{ route('blogs',['category'=>'tutorial']) }}">Learn something new ↗</a></div></section>
@if($pathway=\App\Models\Entry::discoverable()->find($settings?->pathway_id))<section class="pathway"><p class="eyebrow">A PATH TO FOLLOW</p><h2>{{ $pathway->title }}</h2><p>{{ $pathway->summary }}</p><a class="button" href="{{ route('entry',$pathway->slug) }}">Start the journey →</a></section>@endif
<section class="contact-banner forest-clearing"><p class="eyebrow">HERE, IN THIS SEASON</p><h2>Still growing.<br>Always curious.</h2><div class="actions"><a class="text-link" href="{{ route('now') }}">Visit my Now page ↗</a><a class="text-link" href="{{ route('contact') }}">Let’s make something grow ↗</a></div></section>
@endsection
